/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gra;

import com.esotericsoftware.kryonet.Client;
import java.net.InetAddress;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
/**
 *Okienko do wyboru serwera
 * @author Olek
 */
public class ServerList extends javax.swing.JFrame {

    /**
     * Creates new form ServerList
     */
    String host;
    int update=0;
    int Time = 5000;
    public Client client;
    public List<InetAddress> address;
    public Timer zegar;
    public choose abc=new choose();
   
     class bar extends TimerTask{

        @Override
        public void run() {
             address = client.discoverHosts(Network.port+2, Time);
             if(address== null) return;
        
        
        
            String bufor = address.toString(); // format Stringa np. [/127.0.0.1, /127.0.0.1, /192.168.1.101]
            
            char[] buf=bufor.toCharArray();
        
            int a=2;
            int index=0;
        
            String[] adresy=new String[address.size()];
        
            for(int i=0;i<address.size();i++){
                adresy[i]="";
            }
        
            while(buf[a]!=']'){
                if(buf[a]==',') {
                    a+=3;
                    index++;
                    continue;
                }

                adresy[index]+=buf[a];
                a++;
            } 
           jLista.setModel(new javax.swing.DefaultComboBoxModel(adresy));

             jSzukaj.setEnabled(true);
             zegar.cancel();
             
        }
         
     }
    
    class progressBar {
        
        
        
        class Zadanie extends TimerTask{

      
        @Override
        public void run() {
           jProgressBar.setValue(update);
           
           update++; 
           jProgressBar.updateUI();
            
            }      
    
        }
        
        progressBar(){
            
            update=0;          
            zegar = new Timer();
            zegar.scheduleAtFixedRate(new Zadanie(),0,Time/100);
        }
    }
    
    
    
    public ServerList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLista = new javax.swing.JComboBox();
        jSzukaj = new javax.swing.JButton();
        jOK = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jProgressBar = new javax.swing.JProgressBar();
        jServer = new javax.swing.JTextField();
        jOk2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wybierz serwer");

        jLista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "localhost" }));
        jLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaActionPerformed(evt);
            }
        });

        jSzukaj.setText("szukaj");
        jSzukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSzukajActionPerformed(evt);
            }
        });

        jOK.setText("Ok");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });

        jProgressBar.setBounds(10, 0, 333, 14);
        jLayeredPane1.add(jProgressBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jServer.setText("ollon.no-ip.org");

        jOk2.setText("Ok");
        jOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOk2ActionPerformed(evt);
            }
        });

        jLabel1.setText("LAN");

        jLabel2.setText("WAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLista, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jServer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSzukaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jOk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jOK))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSzukaj)
                    .addComponent(jOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOk2))
                .addGap(40, 40, 40)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListaActionPerformed
/**
 * Nacisniecie klawisza Szukaj
 * @param evt 
 */
    private void jSzukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSzukajActionPerformed
        // TODO add your handling code here:
       // progressBar bar = new progressBar();
         client=new Client();

         new progressBar();
         Timer zegar = new Timer();
         zegar.schedule(new bar(), 0);
         jSzukaj.setEnabled(false);

    }//GEN-LAST:event_jSzukajActionPerformed
/**
 * Nacisniecie klawisze OK
 * @param evt 
 */
    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        // TODO add your handling code here:
        host=(String) jLista.getItemAt(jLista.getSelectedIndex());
        
        if(host!=null) {
            abc.put(host);
            setVisible(false);
        }
    }//GEN-LAST:event_jOKActionPerformed

    private void jOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOk2ActionPerformed
        // TODO add your handling code here:
        host = jServer.getText();
        if(host!=null) {
            abc.put(host);
            setVisible(false);
        }
    }//GEN-LAST:event_jOk2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ServerList().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JComboBox jLista;
    private javax.swing.JButton jOK;
    private javax.swing.JButton jOk2;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JTextField jServer;
    private javax.swing.JButton jSzukaj;
    // End of variables declaration//GEN-END:variables
}
